### ISSUE TITLE
OCSP problems when cert renews

### ISSUE THREAD

**Issue by dpisano** [bzed/bzed-dehydrated#17]
Right after your cert renews you will get OCSP errors in Firefox and Chrome if you have OCSP stapling set up.

```
The OCSP response does not include a status for the certificate being verified. Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING
```
Looking at the host it looks like the OCSP file is older than the new cert file. I'm pretty sure I'm getting this error because my system is using the OCSP file for the old cert. It looks like this is happening because the OCSP files is not getting updated after your cert is renewed. Adding something that checks if the cert if newer than the OCSP files should fix this.

**Comment by bzed** [comment]
Hi @dpisano!
10.1.100.3
Thats a good catch, I guess it should be possible to add a workaround for that in puppet - although I'm not exactly sure yet what the best way to handle this is.

The other question that pops up: is that maybe a bug in dehydrated? I'm wondering if it shoudl remove outdated ocsp files...

**Comment by dpisano** [comment]
@bzed could something be added to the runner job?
```
  if cert_still_valid(crt_file) && cert_still_valid(ca_file)
    unless File.exist?(ocsp_file) && (File.mtime(ocsp_file) + 24 * 60 * 60) > Time.now
      stdout, stderr, status = update_ocsp(ocsp_file, crt_file, ca_file)
      return ['OCSP update failed', stdout, stderr, status] if status > 0
    end
  end
```
In the above could some logic be added that compares the `file.mtime` of `ocsp_file` and `crt_file`? If `crt_file` is newer than the `ocsp_file` you would want to call `update_ocsp`.

The only other options that I can think of would be to delete the OCSP file when a cert is made.

**Comment by bzed** [comment]
@dpisano wanna give it a try and create a pull request? :)

**Comment by dpisano** [comment]
@bzed I will give it a shot. I don't know Ruby, but adding an if statement after the unless should not be that hard.

**Comment by bzed** [comment]
@dpisano don't worry, I didn't know ruby before writing that code ;-)

**Comment by dpisano** [comment]
@bzed I submitted the PR. I did some testing on it and it updated the OCSP file if I ran touch on the cert file.
