### ISSUE TITLE
OCSP file update not triggering notify

### ISSUE THREAD

**Issue by dpisano** [bzed/bzed-dehydrated#19]
For some reason when my OCSP files are updated nginx is not getting notified to restart. When that cert is updated the servers is notified and restarts. Bellow is config that I'm using.

```puppet
  dehydrated::certificate { "${myhostname}" : 
      notify  => Service['nginx'],
  }
```

**Comment by dpisano** [comment]
I found the fix for this. It looks like I need to have the `notify` in both `dehydrated::certificate` and on the class.
```puppet
class { 'dehydrated' :
    notify  => Service['nginx'],
}
```

**Comment by bzed** [comment]
> I found the fix for this. It looks like I need to have the `notify` in both `dehydrated::certificate` and on the class.
> 
> ```puppet
> class { 'dehydrated' :
>     notify  => Service['nginx'],
> }
> ```

I think that online should be enough. If I remember right, dehydrated::certificate notifies dehydrated. But I might bw wrong.

**Comment by dpisano** [comment]
I just ran a test and it looks like that one should be enough. Thanks.
