### ISSUE TITLE
Hide secrets

### ISSUE THREAD

**Issue by linuxmail** [bzed/bzed-dehydrated#21]
Hello,

is there a way to keep the credentials / secrets away from diffs (we keep them in eyaml files) ? If I execute the run, than the json file diff will be shown in the logs and on the screen. We want to make sure, that the username/password/api_key is not published.

**Comment by bzed** [comment]
Write your hook script in a way that it will retrieve the credentials based on hostname/certificate/whatever works. There is no need to ship them with puppet...

**Comment by linuxmail** [comment]
hi,

thanks for the hints: I use the hook from [lexicon](https://github.com/AnalogJ/lexicon) and that is a small bash script. So I can just "source" the credentials, without have them in the logs. :-)
