### ISSUE TITLE
Hook / provider define syntax with Hiera: dehydrated::certificates:

### ISSUE THREAD

**Issue by linuxmail** [bzed/bzed-dehydrated#22]
hi,

I saw in this [issue](https://github.com/bzed/bzed-dehydrated/issues/4), that it is possible to overwrite the default. I wonder, how the Hiera syntax is looking. Can you give me a short example ?

cu denny

**Comment by bzed** [comment]
This is an issue tracker, not a help hotline. Please read the documentation. There are examples in the readme and there is the hiera documentation.

**Comment by bzed** [comment]
@linuxmail Thanks a lot for the amazon package!
