### ISSUE TITLE
OCSP update failed for all domains all of a sudden!

### ISSUE THREAD

**Issue by mcblum** [bzed/bzed-dehydrated#27]
Hey! Still using your awesome Puppet module. All of a sudden I see 49 failed certs, all listed as OSCP update failed. Do you happen to know what might have caused that? I think I may need to update to the most recent version of your code / dehydrated, but I also need to read and remember how to do that :)

Hope all is well!

**Comment by mcblum** [comment]
One more bit of information, upgrading to 0.1.8 sends the following error:
```
Error: Path /opt/dehydrated/dehydrated exists and is not the desired repository.
Error: /Stage[main]/Dehydrated::Setup::Dehydrated_host/Vcsrepo[/opt/dehydrated/dehydrated]/ensure: change from 'absent' to 'latest' failed: Path /opt/dehydrated/dehydrated exists and is not the desired repository. (corrective)
```

**Comment by bzed** [comment]
/opt/dehydrated/dehydrated - is probably pretty muc houtdated. The upstream url changed, nothing I can fix.
ocsp might fail because you've been using a way too old module verison.

**Comment by mcblum** [comment]
Thank you!
