### ISSUE TITLE
Intermediate CA Certificate is not changed if the issuer uri stays the same

### ISSUE THREAD

**Issue by gvogets** [bzed/bzed-dehydrated#28]
The letsencrypt change from "DST Root CA X3" to "ISRG Root X1" is not tracked by `dehydrated_job_runner.rb` if the certificate was first issued before the new intermediate CA became the default because the issuer URI stays the same.

**Comment by bzed** [comment]
This should be fixed as we don't track CA urls anymore, CA files are always updated when the cert changes.

fixed with/before
8635c4071dc3e1e2a7f4334d4616ea81b901ebe6
