### ISSUE TITLE
stdlib function "has_key" is deprecated since stdlib 4.x.x and removed in 9.x.x

### ISSUE THREAD

**Issue by pheeef** [bzed/bzed-dehydrated#32]
When installing bzed-dehydrated (1.9) together with stdlib >= 9.0.0 you get the following error

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'has_key'. (file: /etc/puppetlabs/code/environments/production/modules/dehydrated/manifests/init.pp, line: 238, column: 8) on node <FQDN of Puppetserver>
```

Since the has_key is deprecated it should be replaced with something modern. 

https://github.com/puppetlabs/puppetlabs-stdlib/pull/1319

**Comment by pheeef** [comment]
Ok this was apparently fixed in https://github.com/bzed/bzed-dehydrated/commit/f1d7275dca35aa28f2de86d2ba81e1ca668f4796 but the release for release tag is still missing. 

Workaround is to install the puppet-module from source (g10k syntax)
```
mod 'dehydrated',
    :git => 'https://github.com/bzed/bzed-dehydrated.git',
    :branch => 'master'
```

**Comment by bzed** [comment]
Mod updated in forge.
