### ISSUE TITLE
How do I specify which DNS provider / hook to use?

### ISSUE THREAD

**Issue by mcblum** [bzed/bzed-dehydrated#4]
Hi. Some of the domains I'll be requesting certs for are on Cloudflare, others are on Route53. How do I indicate which provider to use when requesting a cert from a host?

Thank you!

**Comment by bzed** [comment]
> Hi. Some of the domains I'll be requesting certs for are on Cloudflare, others are on Route53. How do I indicate which provider to use when requesting a cert from a host?


```
dehydrated::certificate { 'foo.bar.com' : 
   dehydrated_hook => 'route53.sh'
}
```
and then put a route53.sh into $dehydrated_hooks_dir, same for all other kinds of hooks.. If you want you could use a different hook for each certificate.

**Comment by mcblum** [comment]
@bzed awesome -- thank you! I did that, and I first tried it using the prod API. It appears to have worked? At least the config was applied, but I'm left with an `/etc/letsencrypt` folder that has `certs`, `csr`, and `private`. In certs I have a file that ends in `.dh`, in csr is what you'd expect, the .csr, and in  `private` I see the key file, but there's no `live` directory or `.pem` files. Is there any way to see what's actually happening?

Thank you so much for making this! I've been putting this off forever, and I feel like we're finally close to having all certs generated from the same place.

**Comment by mcblum** [comment]
Actually quick update to this -- I do see three files on the Puppet Master - cert-{timestamp}.csr, .pem and privkey-{timestamp}.pem, so it looks like the certs are there. I don't see them transferred back to the host, although maybe I'm just looking in the wrong place?

**Comment by bzed** [comment]
@mcblum look into /opt/dehydrated on your puppet master. That is the host responsible for getting certificates. I know the README is not that long yet, but please read https://github.com/bzed/bzed-dehydrated#usage
In theory you can configure **dehydrated_host** to point to the puppet node itself - it actually works using facter - but the main goal is to get certificates from a central server with internet access to deploy them on machines which are not allowed to conntect to the outside world for whatever reason.

**Comment by bzed** [comment]
@mcblum and there is no timestamp in filenames, so whatever you are seeing is not from bzed-dehydrated.

**Comment by mcblum** [comment]
@bzed Oh I've read through the readme :) We're old friends at this point.

That's exactly what we're trying to do. We have an HA cluster of proxy VMs that are responsible for pulling certs for all of the underlying services. All of those services are accessed through the proxy layer, so basically all certs are generated from a central place.

When I look at my Puppet Master, I don't see any certs folder in `/opt/dehydrated`. Here's what I have there:
![screen shot 2018-12-27 at 4 07 06 pm](https://user-images.githubusercontent.com/1761867/50495909-e8dbd480-09f1-11e9-90ca-a4b38e595ef7.png)

Should there be a certs directory there? Also, I'm happy to pay you for your time! I really appreciate the help with this.

**Comment by bzed** [comment]
> When I look at my Puppet Master, I don't see any certs folder in `/opt/dehydrated`. Here's what I have there:
> ![screen shot 2018-12-27 at 4 07 06 pm](https://user-images.githubusercontent.com/1761867/50495909-e8dbd480-09f1-11e9-90ca-a4b38e595ef7.png)
> 
> Should there be a certs directory there?

So all I can think of are the following issues:

- you did not run puppet often enough on your nodes. Will take at least two puppet runs to transfer the request actually.
- your puppetdb does not work as it should - exported ressources need to work properly.
- the uppetmaster on your nodes points to something else, try to specify it (same as on the puppet master):
```
class { 'dehydrated' :
        dehydrated_host => 'your.dehydrated.host.example.com',
    }
```

**Comment by mcblum** [comment]
@bzed here's a dumb question - does it matter what `your.dehydrated.host.example.com` is? Is that just a domain name that resolves to the IP?

**Comment by bzed** [comment]
> > When I look at my Puppet Master, I don't see any certs folder in `/opt/dehydrated`. Here's what I have there:
> > ![screen shot 2018-12-27 at 4 07 06 pm](https://user-images.githubusercontent.com/1761867/50495909-e8dbd480-09f1-11e9-90ca-a4b38e595ef7.png)

@mcblum ah now I see the issue: your /opt/dehydrated is a git clone of dehydrated. Remove the directory and let puppet create it again (and check the error messages in your puppet run!). Dehydrated itself resides in /opt/dehydrated/dehydrated.

/opt/dehydrated should look like
```
root@foo:/opt/dehydrated# ls -1
acme-challenges
alpn-certs
config.json
dehydrated
dehydrated_job_runner.rb
hooks
monitoring.status
requests
requests.json
status.json
root@foo:/opt/dehydrated# 
```

**Comment by bzed** [comment]
@mcblum your.dehydrated.host.example.com is the $::fqdn of the host you want to run dehydrated on.

**Comment by bzed** [comment]
@mcblum What does
```
facter -p fqdn
```
say on your puppet master?
Puppet that into **dehydrated_host**.

**Comment by mcblum** [comment]
@bzed something is definitely broken:
```
The program 'facter' is currently not installed. You can install it by typing:
apt install facter
```

**Comment by bzed** [comment]
@mcblum please get a proper puppet installation first, including puppetdb. Make sure exported ressources work (and test it...). Then try again. There are consultants to hire close to you for sure.

**Comment by mcblum** [comment]
@bzed will work on it - I didn't know my Puppet installation wasn't working, to be honest. Everything else works just fine and I've never had an issue until now. Sorry to waste your time!

**Comment by bzed** [comment]
There is a new cronjob for the dehydrated user. 
    su - dehydrated
    crontab -l

You can run it manually,  just make sure to do it as user dehydrated.

**Comment by mcblum** [comment]
@bzed hey sweet! Ok, it's running, but the status has been updated to:
```
dehydrated certificates: OK: 0, FAILED: 1
*.domain.com (from edge-proxy-one): CSR signing failed
```
I didn't actually do anything with any CSRs, so I assume that was done behind the scenes?

**Comment by bzed** [comment]
As mentioned before, this is a cronjob. Look into status.json. **AND READ README.md. THESE THINGS ARE ANSWERED THERE.**

**Comment by mcblum** [comment]
But a status of `lock file is present` just means that the second time it tried to run, it couldn't because there was then a lock file, correct? I just assumed that was the result of the cert failing, and then the cron job running again but this time there was a lock file, so I was only getting the most recent error. Maybe that's not the case, though?

**Comment by mcblum** [comment]
Well, I found the solution. Apparently some script along the way needed a package called `publicsuffix` to be installed. Because it wasn't, when Dehydrated went to get the domain ID from Cloudflare, it would fail because it couldn't find a file associated with that package. That error, however, is completely buried so what is outputted to `status.json` doesn't actually tell you what the issue is.

You certainly don't owe me anything and I appreciate the help, but also some meaningful logging in this package would be incredibly helpful. These things are not, in fact, answered in the readme.

**Comment by bzed** [comment]
Well, I can't do more than print the stdout/stderr of dehydrated. If your hook fails and does not log its errors, its either a bug in the hook or in dehydrated. As far as I remember dehydrated logs the hook output....
And yes, I know that having a status.json alone is maybe not the easiest way to find issues, but it was the easiest one to handle this. It logs on failures the stdout, stderr and - always - a summary line for all things that have been executed. Hard to do more.

What you can do is to hack a ```set -x```  into the ```/opt/dehydrated/requests/*/*/*.config``` files and run the cronjob manually. That will give loads of output.... Then figure out how the hook is executed and do this manually. Or add a ```set -x``` (or whatever else works) to the hook script, I'm quite sure that dehydrated will pass on the output.

**Comment by bzed** [comment]
@mcblum does everything work as expected?

**Comment by mcblum** [comment]
@bzed hey man -- thank you for following up. Had the kids the last couple days so was away, but yes, actually things are working great. The certs take, on average, around 10-20 minutes to get back to the hosts but the system is really, really awesome. I'm just in the process now of writing some custom facts so that I can add some config and Puppet will wait for the certs to make it to the host before adding the config to Nginx. 

You were exactly right, Dehydrated was writing the stdout when I looked at the cron job and ran the command manually. I think it was mostly just my not quite understanding exactly how Dehydrated worked and then trying to add it to config management and running into some totally-unrelated troubles. Should have just started there and I would have found the error more quickly!

Thanks for being patient with me and thanks for spending the time on this package. I really appreciate it!

**Comment by bzed** [comment]
@mcblum check the facts from dehydrated. There is one with a 'ready_to_merge' or so in the hash. If that is being set it should be save to add them to the nginx config. Or you can do something like checking if defined(Dehydrated::Certificate::Deploy[$dn]) - should work Ib think.

**Comment by mcblum** [comment]
@bzed sick! thank you for the tip, going to give this a go today!

**Comment by mcblum** [comment]
@bzed I didn't want to open another issue and I SWEAR I read through the readme again first, but how do I recover from an error within the scripts? I didn't realize that one of the scripts I was using needed the cli53 script for Route53 so the process ran, and failed, due to my not having installed that yet.

Is there a way to reset an attempt or make it try again?

**Comment by bzed** [comment]
@mcblum The proper thing is to test with the letsencrypt development CA until everything works. Switching CAs is supported for a reason. The next retry will be done by the cronjob automatically, but you'll hit a rate limit at some point if your code is broken.

**Comment by mcblum** [comment]
@bzed yeah you're absolutely right, I should have done that. I did get everything fixed, but the next cron job (in fact many) have run and looking at `status.json` the text is the same from the failure yesterday, `cli53: command not found` or something like that, but that script is definitely installed now and works when I run it.

If I wanted to just remove that cert request and have it think that it was something new that had not been request yet, is there a way to do that? At least so I can change the CA and see if there's a failure happening still?

**Comment by mcblum** [comment]
In the meantime, yes, I have switched that domain back to staging while I get everything figured out.

**Comment by bzed** [comment]
Just change the CA for the request (or for all),  puppet will do everything for you.

**Comment by mcblum** [comment]
@bzed I had done that and I see that in `requests.json` the `letsencrypt_va_url` has been updated automatically to staging. The strange thing is that the `status.json` file continues to show the same error: `cli53: command not found`. Running that directly as either `root` or `dehydrated` shows me the list of domains, so it's as if even though the CA has been updated, the status hasn't changed since it failed. I had only changed the CA for that one cert and the `requests.json` file looks correct.

**Comment by bzed** [comment]
Did you actually run the cronjob? Manually or wait for it to happen?

**Comment by mcblum** [comment]
Both, actually. I also deleted the relevant files from the host so that when Puppet ran it regenerated everything. Currently the job has just started again I think since it's 3 past the hour, but the request from the domain for one of the servers has now been removed completely, the other one still shows the error. I'm thinking they'll probably sync up after Puppet has run a few times?

**Comment by mcblum** [comment]
Ok! It looks like the issue has been resolved. I basically had to keep running it manually and eventually it started to update status.json with new things. I'm not sure why that didn't happen when the cron job ran, but it appears to be functional now. 

Dude - do you have a Paypal address? Would like to send a thank you for all your help.

**Comment by bzed** [comment]
@mcblum paypal might give me tax troubles, but https://www.amazon.de/hz/wishlist/dl/invite/abceGec might work for you. But I'm happy to help (although I sometimes might sound grumpy when I think people ask things before reading stuff ;)).

Changes in the certificate requests need (I think) two puppet runs on the client and one on the master + a cronjob run + a puppet run on the master + two puppet runs on the client to have all certificates/files back on the client. Thats not such a big issue as you have 30 days to finish the renewal, but for the inital request its long, but there is no proper way around that. I did more things directly in puppet before and that resulted in a way tooooooo long puppet run on master. So I've moved that into a cronjob. Runs fine with several hundred certificates here.

**Comment by mcblum** [comment]
@bzed sweet! I'm on it. Yeah Paypal sucks.

So I think I've sort of isolated the issue after letting everything run overnight. It appears that for whatever reason, the dehydrated_job_runnner.rb script isn't actually running when it should be. If I run it manually by just executing `/opt/dehydrated/dehydrated_job_runner.rb /opt/dehydrated/config.json` I see the `status.json` file updated as soon as the run completes, but only if the script doesn't end with an stdout of `Terminated`. 

I totally agree with you, the timing of the certs is not a big deal at all once it is initially ordered, but I feel like somehow something else got messed up. I just got up and am running the script manually as the `dehydrated` user and it (so far) appears to be running, but none of the runs overnight appeared to have worked. 

Does running it manually mess anything up? I assume I should always be using the `dehydrated` user rather than `root`, correct?

We're processing 8 certs or so, but we're processing them twice (once for each proxy node). Perhaps that is causing issues here? I couldn't figure out a better way to share certs.

Edit: Script just finished:
```
dehydrated@puppet-dev:~$ /opt/dehydrated/dehydrated_job_runner.rb /opt/dehydrated/config.json
Terminated
```

**Comment by mcblum** [comment]
Also, I wasn't able to see your wishlist! And my German sucks, so maybe I'm just not interpreting it correctly :)

**Comment by bzed** [comment]
> So I think I've sort of isolated the issue after letting everything run overnight. It appears that for whatever reason, the dehydrated_job_runnner.rb script isn't actually running when it should be. If I run it manually by just executing `/opt/dehydrated/dehydrated_job_runner.rb /opt/dehydrated/config.json` I see the `status.json` file updated as soon as the run completes, but only if the script doesn't end with an stdout of `Terminated`.

Terminated sounds.... buggy! Right now I'm wondering what actually prints this, as the stdout + stderr of all programs that are being executed is collected and written into the reults.json in case of issues.
Does that also happen if you run it manually? Or is that the cronjob output?

> Does running it manually mess anything up? I assume I should always be using the `dehydrated` user rather than `root`, correct?

correct. All files in /opt/dehydrated should also be owned by dehydrated, requests.json being the only exception.
 
> We're processing 8 certs or so, but we're processing them twice (once for each proxy node). Perhaps that is causing issues here? I couldn't figure out a better way to share certs.

no, thats perfectly fine.

> ```
> dehydrated@puppet-dev:~$ /opt/dehydrated/dehydrated_job_runner.rb /opt/dehydrated/config.json
> Terminated
> ```

So that also happens if you run it manually.... You are running Ubuntu, correct? If so, please check the apparmor logs. Thats the only idea I actually have. If that does not help, please install strace and run

```strace -vfF /opt/dehydrated/dehydrated_job_runner.rb /opt/dehydrated/config.json```

And post the last 20-30 lines before Terminated is being printed. Make sure to replace all usernames/passwords and other sensitive information before posting ;) Check twice....

**Comment by mcblum** [comment]
> Does that also happen if you run it manually? Or is that the cronjob output?
That is what happens if I run it manually.

> Correct. All files in /opt/dehydrated should also be owned by dehydrated, requests.json being the only exception.
That's exactly what I have. I did once see an error that said "cannot access /requets/{domain}/something" and somehow that file had been set to `root:root`, but I fixed that. Currently the only file owned by `root:root` is `requests.json`.

> No, thats perfectly fine.
Sweet! The whole reason I had to double back on this is that proxy one had all certs working great as of yesterday, and proxy two had one cert that was downloaded to the host but made Nginx throw an error about the private keys not matching. I assumed that had something to do with requesting a cert for each host.

> You are running Ubuntu, correct? If so, please check the apparmor logs. Thats the only idea I actually have. If that does not help, please install strace and run.
The results of `strace` are:
```
[pid 63870] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=63875, si_uid=1001, si_status=0, si_utime=0, si_stime=0} ---
[pid 63870] wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 63875
[pid 63870] wait4(-1, 0x7ffd29358810, WNOHANG, NULL) = -1 ECHILD (No child processes)
[pid 63870] rt_sigreturn({mask=[]})     = 0
[pid 63870] close(4)                    = 0
[pid 63870] rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
[pid 63870] rt_sigaction(SIGINT, {0x4449b0, [], SA_RESTORER, 0x7fe7529e94b0}, {0x45fa10, [], SA_RESTORER, 0x7fe7529e94b0}, 8) = 0
[pid 63870] rt_sigaction(SIGINT, {0x45fa10, [], SA_RESTORER, 0x7fe7529e94b0}, {0x4449b0, [], SA_RESTORER, 0x7fe7529e94b0}, 8) = 0
[pid 63870] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 63870] fcntl(1, F_GETFD)           = 0
[pid 63870] fcntl(1, F_DUPFD, 10)       = 10
[pid 63870] fcntl(1, F_GETFD)           = 0
[pid 63870] fcntl(10, F_SETFD, FD_CLOEXEC) = 0
[pid 63870] dup2(2, 1)                  = 1
[pid 63870] fcntl(2, F_GETFD)           = 0
[pid 63870] write(1, "ERROR: CloudFlare request failed"..., 33) = 33
[pid 63870] dup2(10, 1)                 = 1
[pid 63870] fcntl(10, F_GETFD)          = 0x1 (flags FD_CLOEXEC)
[pid 63870] close(10)                   = 0
[pid 63870] brk(0x1593000)              = 0x1593000
[pid 63870] fcntl(1, F_GETFD)           = 0
[pid 63870] fcntl(1, F_DUPFD, 10)       = 10
[pid 63870] fcntl(1, F_GETFD)           = 0
[pid 63870] fcntl(10, F_SETFD, FD_CLOEXEC) = 0
[pid 63870] dup2(2, 1)                  = 1
[pid 63870] fcntl(2, F_GETFD)           = 0
[pid 63870] write(1, "ERROR: Response: {\"success\":fals"..., 180) = 180
[pid 63870] dup2(10, 1)                 = 1
[pid 63870] fcntl(10, F_GETFD)          = 0x1 (flags FD_CLOEXEC)
[pid 63870] close(10)                   = 0
[pid 63870] kill(0, SIGTERMstrace: Process 61251 detached
strace: Process 61252 detached
strace: Process 63612 detached
strace: Process 63614 detached
strace: Process 63613 detached
strace: Process 63615 detached
strace: Process 63616 detached
strace: Process 63865 detached
strace: Process 63866 detached
strace: Process 63869 detached
strace: Process 63870 detached
 <detached ...>
strace: Process 63871 detached
```
Looks like it's a Cloudflare issue or something? That's super weird -- that was the first thing that was working before.

**Comment by mcblum** [comment]
Restarted the VM, put all env variables in `/etc/environment` rather than in the `.bashrc` file and I think it appears to be working. Been running for 5-10 minutes with no errors!

**Comment by bzed** [comment]
> Also, I wasn't able to see your wishlist! And my German sucks, so maybe I'm just not interpreting it correctly :)

https://www.amazon.com/hz/wishlist/dl/invite/5ahN5E7 - try this one :)

**Comment by bzed** [comment]
> Restarted the VM, put all env variables in `/etc/environment` rather than in the `.bashrc` file and I think it appears to be working. Been running for 5-10 minutes with no errors!

You could just put environment variables into the ```dehydrated_environment`` hash in each dehydrated::certificate or as default when you define the dehydrated class. With that its possible to configure the environment for each certificate...

Guess I should add some more documentation to https://bzed.github.io/bzed-dehydrated/puppet_defined_types/dehydrated_3A_3Acertificate.html .... :)

**Comment by bzed** [comment]
@mcblum ah I fear you'll have to live with the wishlist link above, the amazon.com one is not my german account :(

**Comment by bzed** [comment]
@mcblum so yes, its https://www.amazon.de/hz/wishlist/dl/invite/abceGec - if you go to https://www.amazon.de first I think you should get the english version. At least thats what I sometimes get ... for login the amazon.com credentials should work I think.

**Comment by mcblum** [comment]
Hm - got this:
`Es ist ein Fehler aufgetreten. Wir können Sie derzeit nicht zu dieser Liste hinzufügen. Bitte versuchen Sie es später erneut.`

**Comment by bzed** [comment]
@mcblum that means that they can't add you to the list. seems it tracks who acutally accessed the list. I've clicked on 'send invitation by email' now and it generated a different link... https://www.amazon.de/hz/wishlist/dl/invite/3U6QKbh

**Comment by bzed** [comment]
@mcblum and now I've got a totally different one, seems the amazon people are changing things: https://www.amazon.de/registry/wishlist/1TXINPFZU79GL

**Comment by bzed** [comment]
@mcblum https://bzed.github.io/bzed-dehydrated/puppet_defined_types/dehydrated_3A_3Acertificate.html - a bit more documentation :)

**Comment by mcblum** [comment]
@bzed got the list working! Do you boulder? I just started 6 months ago. Also happen to be a photographer, so there's a bit over overlapping interest! We did a bunch of shoots in Germany a couple years ago (NSFW) https://thenuproject.com

**Comment by bzed** [comment]
@mcblum I'm doing a lot of mountain sports, photography, lots of linux stuff, music, ... way too many hobbies ;)

**Comment by mcblum** [comment]
@bzed sick! Will pick something out this evening. If you're on Instagram, send your handle so I can follow along!

**Comment by bzed** [comment]
Cool,  thanks! I'm bzed_81 on insta.
