### ISSUE TITLE
Some config questions

### ISSUE THREAD

**Issue by dpisano** [bzed/bzed-dehydrated#9]
I'm in the presses of testing dehydrated so that I can migrate from the letsencrypt module. I'm using the following config has part of my testing.

On the dehydrated host:
```puppet
  class { 'dehydrated' :
      dehydrated_host          => 'puppet.example.com',
      letsencrypt_ca           => 'staging',
      dehydrated_contact_email => 'email@example.com',
      dehydrated_hook          => 'hook.py',
      dehydrated_environment   => {
          'CF_EMAIL' => 'your@email.address',
          'CF_KEY'   => 'your-long-Cloudflare-api-key',
      }
  }
```
One host that are requesting certs:
```puppet
  class { 'dehydrated' :
      dehydrated_host => 'puppet.example.com',
      group    => 'letsencrypt',
      base_dir => '/etc/letsencrypt',
  }

  dehydrated::certificate { 'host.example.com' : 
      notify  => Service['nginx'],
  }
``` 
 When I look at the `requests.json` on the dehydrated host I see that `letsencrypt_ca_url` is set to `https://acme-v02.api.letsencrypt.org/directory` and `dehydrated_hook_script` is set to `/opt/dehydrated/hooks/dns-01.sh`. Given the config that I have on the dehydrated host I'm expecting `letsencrypt_ca_url` to be set to the staging CA and `dehydrated_hook_script` to be set to `/opt/dehydrated/hooks/hook.py`. Am I misunderstanding how this should be setup? Do `letsencrypt_ca` and `dehydrated_hook` need to be set on each host? I know that `dehydrated_hook` can be set for each `dehydrated::certificate`, but I figured it would default to what was set on the dehydrated host when it was not set.

Also is there a way to manually run the cron job to make the certificate requests?

**Comment by dpisano** [comment]
Also from some of my testing it looks like I have to have `dehydrated_environment` set on each of my host. This seems to be inconsistent with the documentation which seems indicate that it is only needed on the `dehydrated_host`.

**Comment by bzed** [comment]
You should be able to set the environment for each single certificate.  If you don't do that,  the environment of the host where you request the certificate will be used.  I don't think it's using the environment from your dehydrated_host.

For the cronjob - 
   crontab -l -u dehydrated
will show you the command.

**Comment by bzed** [comment]
I'll send a better reply after my holidays.

**Comment by dpisano** [comment]
Thanks, this helps. In the mean time I will do some more testing.

**Comment by bzed** [comment]
> ....
> With this setup I will see errors in `status.json` that indicate that the cloudflare environment variables are missing.
> I did find something interesting when I was testing. If I set `dehydrated_environment` on a host requesting a cert, that cert and any cert listed in `requests.json` below it would work.



yes, basically the full config snippet for the certificate comes from the host that is requesting the certificate. It is just an exported ressource being collected. There is no magic config merge or so happening here.

If you have global environment variables, you could just add them to your hook script...

 
> Also on a side note it might be good to add to the README that ruby needs to be installed on the `dehydrated_host`.

The cronjob is taking the $PATH from puppet, which should contain the ruby version delivered with your puppet agent. So far this always worked for me, if it does not, I'd need your help to fix it.
If you have a puppet agent that was shipped with your distribution, it should also depend on ruby.

**Comment by dpisano** [comment]
>yes, basically the full config snippet for the certificate comes from the host that is requesting the certificate. It is just an exported ressource being collected. There is no magic config merge or so happening here.
>
>If you have global environment variables, you could just add them to your hook script...

After all the testing that I have done that was the conclusion I had come to. The README made it seam like it worked work differently. I had put my environment variables in hook script as a workaround anyway, so I will just leave it like that.

For ruby I'm using the puppetlabs version of the agent, so it does have ruby include with it. The path set in the cronjob is `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/puppetlabs/bin`. The ruby the comes with puppet is in `/opt/puppetlabs/puppet/bin` so it would not be in the path that is set. Also as a node that cronjob PATH is only set when I run puppet manually. When it runs as a service `/opt/puppetlabs/bin` will be missing from the PATH. Let me know if there are any test you would like me to run or if you need anymore information. The OS is Debian 9 and I'm running Puppet 5.

**Comment by bzed** [comment]
@dpisano could you give it a try now please?

**Comment by dpisano** [comment]
I tested it in my dev environment and it works as I would expect it to. I don't have to install ruby on the system for it to work now. It is using the version of ruby that comes with puppet now.
